[context.branch-deploy.environment]
  NEXT_STAGING_ENV = "stg"
  NEXT_USE_NETLIFY_EDGE = "true"

[build]
  command = 'yarn build'
  publish = '.next'
  functions = 'out_functions'

[[plugins]]
  package = "@netlify/plugin-nextjs"